name: Preservation Operations
description: Initiate preservation workflow.
title: "Validating Records & Files for Preservation"
labels: ["preservation"]
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > The metadata records and digital files must exist prior to beginning this workflow.
  - type: checkboxes
    id: approval
    attributes:
      label: Manual Approval
      description: Manual approval of validation results will be required to execute the workflow.
      options:
        - label: I will monitor this issue and respond to the validation results.
          required: true
