name: Preservation Issue Parser

on:
  issues:
    types: opened

jobs:
  validate:
    runs-on: ubuntu-latest
    if: ${{ !github.event.issue.pull_request && contains(github.event.issue.labels.*.name, 'preservation') }}
    steps:
      - uses: actions/checkout@v4

      - name: Check for blocking issues
        run: |
          blockers="$(gh issue list --search "label:attention,failure" --json number --jq '"- #\(.[].number)"')"
          if [ -n "$blockers" ]; then
            gh issue edit ${{ github.event.issue.number }} \
              --add-label "failure" \
              --title "Open Issues Blocking Preservation Workflow"
            COMMENT_BODY=$(echo -e "This issue and the following issues must be closed before the preservation workflow can run:\n\n${blockers}")
            gh issue comment ${{ github.event.issue.number }} --body "$COMMENT_BODY"
            gh issue edit ${{ github.event.issue.number }} --add-assignee ${{ github.actor }}
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run validation code
        id: script
        run: |
          echo "run validation" &>> ${RUNNER_TEMP}/validation.log
          echo "python ${HOME}/${GITHUB_REPOSITORY}/s3.py &>> ${RUNNER_TEMP}/validation.log" &>> ${RUNNER_TEMP}/validation.log
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment with success output
        if: always() && steps.script.outcome == 'success'
        run: |
          gh issue edit ${{ github.event.issue.number }} \
            --add-label "attention" \
            --title "Review Validation for Preservation Workflow"
          LOG=$(cat "${RUNNER_TEMP}/validation.log")
          CODEBLOCK_FENCE='```'
          CODEBLOCK=$(echo -e "$CODEBLOCK_FENCE\n$LOG\n$CODEBLOCK_FENCE")
          COMMENT_BODY=$(echo -e "$CODEBLOCK\nReply with a new comment containing the text **OK** to approve the validation results and continue the workflow execution.")
          gh issue comment ${{ github.event.issue.number }} --body "$COMMENT_BODY"
          gh issue edit ${{ github.event.issue.number }} --add-assignee ${{ github.actor }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment with failure output
        if: always() && steps.script.outcome != 'success' && steps.script.outcome != 'skipped'
        run: |
          gh issue edit ${{ github.event.issue.number }} \
            --add-label "failure" \
            --title "Failed Validation for Preservation Workflow"
          LOG=$(cat "${RUNNER_TEMP}/validate.log")
          CODEBLOCK_FENCE='```'
          CODEBLOCK=$(echo -e "$CODEBLOCK_FENCE\n$LOG\n$CODEBLOCK_FENCE")
          gh issue comment ${{ github.event.issue.number }} --body "$CODEBLOCK"
          gh issue edit ${{ github.event.issue.number }} --add-assignee ${{ vars.DEVELOPER }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
